version: '3.4'

services:
  db-book:
    image: kvarc/final-test-docker:latest
    ports:
      - 8081:8081
    container_name: db-book
    networks:
      - book-network
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - book-network
    ports:
      - 27018:27017

networks:
  book-network:
    name: book-network