apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
  labels:
    app: add
spec:
  selector:
    matchLabels:
      app: add
  replicas: 1
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
        - name: app
          image: kvarc/final-test-mongo-v-2:latest
          ports:
            - name: add-server
              containerPort: 8081
        - image: mongo
          ports:
            - name: add-service
              containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: hello-k3s
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: server

