version: '3.3'

services:
  db-book:
    image: ${SERVER_IMAGE}
    environment:
     - DB_USERS_USER=${DB_USER}
     - DB_USERS_PASSWORD=${DB_PASSWORD}
     - DB_USERS_HOST=${DB_HOST}
     - DB_USER_PORT=${DB_PORT}
    ports:
      - 8081:8081
    container_name: ${SERVER_CONTAINER_NAME}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - ${DB_MONGO}
  mongo:
    container_name: ${DB_MONGO}
    image: ${MONGO_IMAGE}
    ports:
      - 27018:27017
    networks:
      - ${NETWORK_NAME}

networks:
  book-network:
    name: ${NETWORK_NAME}