apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - name: add-service
              containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: add-service