apiVersion: v1
kind: Service
metadata:
  name: spring-mongo-service
spec:
  type: LoadBalancer
  selector:
    app: spring-mongo-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-service
spec:
  selector:
    matchLabels:
      app: spring-mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-mongo-service
    spec:
      containers:
        - name: spring-mongo-service
          image: kvarc/final-test-docker:latest
          ports:
            - containerPort: 8081