apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deploy
spec:
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
      - image: kvarc/final-test-mongo-v-2:latest
        name: container1
        imagePullPolicy: IfNotPresent
        

apiVersion: v1
kind: Service
metadata:
  name: todo-client-service
spec:
  selector:
    app: todo-client-app
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer
